# coding: utf-8

"""
    otp OTP API

    Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from otp_sdk.api.otp_api import OTPApi


class TestOTPApi(unittest.TestCase):
    """OTPApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OTPApi()

    def tearDown(self) -> None:
        pass

    def test_get_otp_status(self) -> None:
        """Test case for get_otp_status

        Get OTP status
        """
        pass

    def test_resend_otp(self) -> None:
        """Test case for resend_otp

        Resend an OTP
        """
        pass

    def test_send_otp(self) -> None:
        """Test case for send_otp

        Send an OTP
        """
        pass

    def test_verify_otp(self) -> None:
        """Test case for verify_otp

        Verify an OTP
        """
        pass


if __name__ == '__main__':
    unittest.main()
