# coding: utf-8

"""
    otp OTP API

    Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from otp_sdk.models.otp_response import OtpResponse

class TestOtpResponse(unittest.TestCase):
    """OtpResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OtpResponse:
        """Test OtpResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OtpResponse`
        """
        model = OtpResponse()
        if include_optional:
            return OtpResponse(
                otp_id = '',
                status = 'pending',
                channel = 'sms',
                masked_recipient = ''
            )
        else:
            return OtpResponse(
                otp_id = '',
                status = 'pending',
                channel = 'sms',
                masked_recipient = '',
        )
        """

    def testOtpResponse(self):
        """Test OtpResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
