# coding: utf-8

# flake8: noqa
"""
    otp OTP API

    Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from otp_sdk.models.channel import Channel
from otp_sdk.models.error import Error
from otp_sdk.models.error_error import ErrorError
from otp_sdk.models.otp_response import OtpResponse
from otp_sdk.models.otp_status_response import OtpStatusResponse
from otp_sdk.models.resend_request import ResendRequest
from otp_sdk.models.send_request import SendRequest
from otp_sdk.models.status import Status
from otp_sdk.models.verify_request import VerifyRequest
from otp_sdk.models.verify_response import VerifyResponse

