# coding: utf-8

# flake8: noqa
"""
    otp OTP API

    Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API.  Errors are always `{\"error\": {\"type\", \"message\", \"details\"?}}`.  When routing picks WhatsApp the code is not sent yet: the send response carries an `action_url` (a wa.me link) the user opens to receive the code over WhatsApp, and the OTP stays pending until they enter it. Verification is identical on every channel.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from otp_sdk.models.channel import Channel
from otp_sdk.models.error_body import ErrorBody
from otp_sdk.models.error_response import ErrorResponse
from otp_sdk.models.otp_response import OtpResponse
from otp_sdk.models.otp_status_response import OtpStatusResponse
from otp_sdk.models.resend_request import ResendRequest
from otp_sdk.models.send_request import SendRequest
from otp_sdk.models.status import Status
from otp_sdk.models.verify_request import VerifyRequest
from otp_sdk.models.verify_response import VerifyResponse

