# coding: utf-8

"""
    otp OTP API

    Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API.  Errors are always `{\"error\": {\"type\", \"message\", \"details\"?}}`.  When routing picks WhatsApp the code is not sent yet: the send response carries an `action_url` (a wa.me link) the user opens to receive the code over WhatsApp, and the OTP stays pending until they enter it. Verification is identical on every channel.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Channel(str, Enum):
    """
    Channel the OTP was dispatched on; null until routed.
    """

    """
    allowed enum values
    """
    SMS = 'sms'
    WHATSAPP = 'whatsapp'
    EMAIL = 'email'
    TELEGRAM = 'telegram'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Channel from a JSON string"""
        return cls(json.loads(json_str))


