# coding: utf-8

# flake8: noqa

"""
    otp OTP API

    Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API.  Errors are always `{\"error\": {\"type\", \"message\", \"details\"?}}`.  When routing picks WhatsApp the code is not sent yet: the send response carries an `action_url` (a wa.me link) the user opens to receive the code over WhatsApp, and the OTP stays pending until they enter it. Verification is identical on every channel.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "OTPApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Channel",
    "ErrorBody",
    "ErrorResponse",
    "OtpResponse",
    "OtpStatusResponse",
    "ResendRequest",
    "SendRequest",
    "Status",
    "VerifyRequest",
    "VerifyResponse",
]

# import apis into sdk package
from otp_sdk.api.otp_api import OTPApi as OTPApi

# import ApiClient
from otp_sdk.api_response import ApiResponse as ApiResponse
from otp_sdk.api_client import ApiClient as ApiClient
from otp_sdk.configuration import Configuration as Configuration
from otp_sdk.exceptions import OpenApiException as OpenApiException
from otp_sdk.exceptions import ApiTypeError as ApiTypeError
from otp_sdk.exceptions import ApiValueError as ApiValueError
from otp_sdk.exceptions import ApiKeyError as ApiKeyError
from otp_sdk.exceptions import ApiAttributeError as ApiAttributeError
from otp_sdk.exceptions import ApiException as ApiException

# import models into sdk package
from otp_sdk.models.channel import Channel as Channel
from otp_sdk.models.error_body import ErrorBody as ErrorBody
from otp_sdk.models.error_response import ErrorResponse as ErrorResponse
from otp_sdk.models.otp_response import OtpResponse as OtpResponse
from otp_sdk.models.otp_status_response import OtpStatusResponse as OtpStatusResponse
from otp_sdk.models.resend_request import ResendRequest as ResendRequest
from otp_sdk.models.send_request import SendRequest as SendRequest
from otp_sdk.models.status import Status as Status
from otp_sdk.models.verify_request import VerifyRequest as VerifyRequest
from otp_sdk.models.verify_response import VerifyResponse as VerifyResponse

